source 'https://rubygems.org'
ruby '3.1.3'

gem 'sii_chile', path: 'gem'
gem 'sinatra'
gem 'rack-contrib'
gem 'dalli'
gem 'memcachier'
gem 'puma'
gem 'multi_json'
gem 'newrelic_rpm'
gem 'statsmix'
gem 'rspec', '~> 3.12.0'
